seed_everything: 42
ckpt_path: null # for checkpointing

data:
  class_path: modules.datasets.rae.RAEDataModule
  init_args:
    batch_size: 16
    num_workers: 0
    normalize: True

trainer:
  max_epochs: 100 
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      name: run_24-02-2024-13:00:00
      project: RAE_DCGAN
      offline: False
      save_dir: ./log
  callbacks: 
    - class_path: modules.callbacks.ImageLogger
      init_args:
        batch_frequency: 1000
        max_images: 8
        rescale: False

model:
  class_path: models.GAN.dcgan.DCGAN
  init_args:
    train_imbalance: 0.1
    config:
      lr_gen: 0.0002
      lr_dis: 0.0002
      b1: 0.5
      b2: 0.999
      in_channels: 8
      image_size: 
        - 64
        - 64
      base_channels: 16
      channel_multipliers:
        - 2
        - 4
        - 8
        - 16
        - 32
      bias: False
      latent_dim: 128
      final_activation: 
        class_path: torch.nn.modules.activation.Sigmoid