seed_everything: 42
ckpt_path: null

data:
  class_path: modules.datasets.mnist.MNISTDataModule
  init_args:
    batch_size: 128

model:
  class_path: models.MLP.MLP
  init_args:
    input_dim:
      - 1
      - 28
      - 28
    layer_dims:
      - 128
      - 64
      - 32
    output_dim: 10
    final_activation: 
      class_path: torch.nn.Sigmoid
    activation:
      class_path: torch.nn.SiLU
    image_key: image
    target_key: label
    learning_rate: 1e-4
    loss:
      class_path: torch.nn.BCELoss

trainer:
  max_epochs: 100
  log_every_n_steps: 1000
#  logger:
#    class_path: pytorch_lightning.loggers.WandbLogger
#    init_args:
#      project: MyProject
#      log_model: all
#      offline: False