seed_everything: 42
ckpt_path: null

model:
  class_path: models.autoencoder.vqvae.VQVAE
  init_args:
    learning_rate: 0.002
    betas: 
      - 0.9
      - 0.99
    config:
      in_channel: 1
      base_channel: 16
      z_channels: 2
      channel_multipliers:
        - 1
        - 2
        - 4
      num_res_blocks: 1
      dropout: 0.1
      norm: bn
      attention_resolutions:
        - 1
    num_embeddings: 100

data:
  class_path: modules.datasets.mnist.MNISTDataModule
  init_args:
    batch_size: 128

trainer:
  max_epochs: 1000

  callbacks: 
    - class_path: modules.callbacks.ImageLogger
      init_args:
        batch_frequency: 10000
        max_images: 8
        rescale: False
