seed_everything: 42
ckpt_path: null

model:
  class_path: models.autoencoder.vanilla.VanillaAE
  init_args:
    enc_config:
      in_channel: 1
      base_channel: 16
      z_channels: 1
      channel_multipliers:
        - 2
        - 4
      num_res_blocks: 1
      dropout: 0.1
      norm: bn
      attention_resolutions:
        - 1

    dec_config:
      out_channels: 1
      base_channel: 16
      z_channels: 1
      channel_multipliers:
        - 2
        - 4
      num_res_blocks: 1
      dropout: 0.1
      norm: bn
      attention_resolutions:
        - 1
      
    loss:
      class_path: torch.nn.MSELoss   

data:
  class_path: modules.mnist.MNISTDataModule
  init_args:
    batch_size: 128

trainer:
  max_epochs: 1000
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      name: test
      project: MINST_VAE
      offline: False
      save_dir: ./log

  callbacks: 
    - class_path: modules.callbacks.ImageLogger
      init_args:
        batch_frequency: 1000
        max_images: 8
        rescale: True
