seed_everything: 42
ckpt_path: null # for checkpointing

data:
  class_path: modules.rae.RAEDataModule
  init_args:
    batch_size: 16
    num_workers: 4
    normalize: True

trainer:
  max_epochs: 100 
  callbacks: 
    - class_path: modules.callbacks.ImageLogger
      init_args:
        batch_frequency: 100
        max_images: 8
        rescale: False

