seed_everything: 42
ckpt_path: null

data:
  class_path: modules.datasets.rae.RAEDataModule
  init_args:
    batch_size: 16
    num_workers: 0
    normalize: True
    subset: img_64x64

trainer:
  max_epochs: 1000 
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: RAE_64x64_VQVAE
      offline: False
      save_dir: ./log
  callbacks: 
    - class_path: modules.callbacks.ImageLogger
      init_args:
        batch_frequency: 1000
        max_images: 8
        rescale: False
#    - class_path: lightning.pytorch.callbacks.DeviceStatsMonitor
#      init_args:
#        cpu_stats: True
# TEST model
model:
  class_path: models.autoencoder.vqvae.VQVAE
  init_args:
    kl_weight: 0.01
    commitment_scale: 0.25
    learning_rate: 0.0002
    image_key: "field"
    num_embeddings: 512
    betas: 
      - 0.5
      - 0.9
    config:
      in_channel: 6
      base_channel: 16
      z_channels: 128
      double_z: True
      channel_multipliers:
        - 2
        - 4
        - 8
        - 16
        - 32
      num_res_blocks: 2
      dropout: 0.0
      norm: bn
      attention_resolutions:
        - 1
        - 2
        - 3
