seed_everything: 42
ckpt_path: null # for checkpointing

data:
  class_path: modules.datasets.rae.RAEDataModule
  init_args:
    batch_size: 16
    num_workers: 0
    normalize: True
    subset: img_64x64

trainer:
  max_epochs: 1000 
#  logger:
#    class_path: lightning.pytorch.loggers.WandbLogger
#    init_args:
#      name: run_1
#      project: RAE_DEEPFLOW_VAE
#      offline: False
#      save_dir: ./log
  callbacks: 
    - class_path: modules.callbacks.ImageLogger
      init_args:
        batch_frequency: 1000
        max_images: 8
        rescale: False

# TEST model
model:
  class_path: models.autoencoder.deepflow.DeepFlowVQVAE
  init_args:
    image_key: "field"
    learning_rate: 0.002
    betas: 
      - 0.9
      - 0.99
    latent_dim: 128
    kl_weight: 0.000001
    config:
      input_shape: 
        - 8
        - 64
        - 64
      base_channel: 32
      image_layers: 2
      num_heads: 4
      dropout: 0.0
      norm: bn
      
